### ISSUE TITLE
[Question]: Page width 

### ISSUE THREAD

**Issue by aeq-dev** [Quadrubo/filament-model-settings#4]
### What happened?

I checked ModelSettingsPage page and I found this piece of code:
```
 protected function getForms(): array
    {
        return [
            'form' => $this->form(
                $this->makeForm()
                    ->statePath('data')
                    ->columns(2)
                    ->inlineLabel($this->hasInlineLabels()),
            ),
        ];
    }
```
Why did you set columns to 2? how can we update it to fit the page width ?

### How to reproduce the bug

-

### Package Version

1.0.1

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

Linux

**Comment by Quadrubo** [comment]
I just implemented this the way the core team did for the "Spatie Settings" package.
I think of it as a sensible default but am of course open for discussion.

If you have a field inside the form it spans 1 column by default:

```php
public function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\TextInput::make('test'),
        ]);
}
```

Now if you want to make it occupy the whole page, you can just add `->columnSpan(2)` to it.

```php
public function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\TextInput::make('test')
                ->columnSpan(2),
        ]);
}
```

You can then also add a Layout around it which spans 2 columns and offers a single column to the children:

```php
public function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\Grid::make(1)
                ->schema([
                    Forms\Components\TextInput::make('test'),
                ])
                ->columnSpan(2),
        ]);
}
```

Let me know if this solves your issue :)
